"""
Problem Title:Smart Airline Reservation Analytics using Pandas

Problem Statement:

An airline company maintains passenger reservation
details in multiple CSV files.

The management wants to analyze airline bookings
using the Pandas library.

Three CSV files are available.

Passenger File contains:

Passenger ID
Passenger Name
City

Flight File contains:

Flight ID
Airline
Destination

Booking File contains:

Booking ID
Passenger ID
Flight ID
Ticket Fare

The program should perform the following operations.

Step 1:Load all three CSV files using Pandas.
Step 2:Merge Passenger and Booking datasets using Passenger ID.
Step 3: Merge the above result with Flight dataset using Flight ID.
Step 4: Display the complete reservation report.
Step 5:Using loc(),display all passengers travelling to Dubai.
Step 6:Using iloc(),display the third and fourth reservation records.
Step 7:Using groupby(),display the total revenue generated by each airline.
Step 8:Display the airline generating the highest revenue.

Requirements
------------

1. Read passengers.csv.
2. Read flights.csv.
3. Read bookings.csv.
4. Merge multiple DataFrames.
5. Use loc().
6. Use iloc().
7. Use groupby().
8. Display highest revenue airline.

Input Files
-----------
passengers.csv
flights.csv
bookings.csv

Output Format
-------------
Complete Reservation Report
...
Passengers Travelling to Dubai
...
Third and Fourth Reservations
...
Airline Revenue Report
...
Highest Revenue Airline
...


Sample passengers.csv
---------------------
PassengerID,PassengerName,City
P101,Ravi,Hyderabad
P102,Priya,Chennai
P103,Rahul,Bangalore
P104,Anu,Hyderabad
P105,Kiran,Mumbai




Sample flights.csv
------------------
FlightID,Airline,Destination
F101,IndiGo,Dubai
F102,AirIndia,Singapore
F103,Emirates,Dubai
F104,Vistara,London


Sample bookings.csv
-------------------
BookingID,PassengerID,FlightID,TicketFare
B101,P101,F101,25000
B102,P102,F102,30000
B103,P103,F103,45000
B104,P104,F101,27000
B105,P105,F104,50000


case=1
output=
Complete Reservation Report
B101 Ravi Hyderabad IndiGo Dubai 25000
B102 Priya Chennai AirIndia Singapore 30000
B103 Rahul Bangalore Emirates Dubai 45000
B104 Anu Hyderabad IndiGo Dubai 27000
B105 Kiran Mumbai Vistara London 50000

Passengers Travelling to Dubai
Ravi IndiGo 25000
Rahul Emirates 45000
Anu IndiGo 27000

Third and Fourth Reservations
B103 Rahul Emirates 45000
B104 Anu IndiGo 27000

Airline Revenue Report
IndiGo 52000
Vistara 50000
Emirates 45000
AirIndia 30000

Highest Revenue Airline
IndiGo 52000


Step 1:Load all three CSV files using Pandas.
Step 2:Merge Passenger and Booking datasets using Passenger ID.
Step 3: Merge the above result with Flight dataset using Flight ID.
Step 4: Display the complete reservation report.
Step 5:Using loc(),display all passengers travelling to Dubai.
Step 6:Using iloc(),display the third and fourth reservation records.
Step 7:Using groupby(),display the total revenue generated by each airline.
Step 8:Display the airline generating the highest revenue.

"""
import pandas as pd
pdf=pd.read_csv("passengers.csv")
fdf=pd.read_csv("flights.csv")
bdf=pd.read_csv("bookings.csv")
mdf1=pd.merge(pdf,bdf,on="PassengerID")
mdff=pd.merge(mdf1,fdf,on="FlightID")
fin=mdff[["BookingID","PassengerName","City","Airline","Destination","TicketFare"]]
fin1=fin.sort_values(by="BookingID")
print("Complete Reservation Report")
print(fin1.to_string(index=False,header=False))
print()
print("Passengers Travelling to Dubai")
ptd=mdff.loc[mdff["Destination"]=="Dubai",["PassengerID","PassengerName","Airline","TicketFare"]]
ptdf=ptd.sort_values(by="PassengerID")
ptdff=ptdf.loc[:,["PassengerName","Airline","TicketFare"]]
print(ptdff.to_string(index=False,header=False))
print()
print("Third and Fourth Reservations")
f1=fin1.loc[:,["BookingID","PassengerName","Airline","TicketFare"]]
f2=f1.iloc[2:4]
print(f2.to_string(index=False,header=False))
print()
print("Airline Revenue Report")
revenue=mdff.groupby("Airline")["TicketFare"].sum()
revenue=revenue.sort_values(ascending=False)
print(revenue.to_string(header=False))
print()
print("Highest Revenue Airline")
print(revenue.iloc[0:1].to_string(header=False))
